### ISSUE TITLE
apk of BraveNewPipe?

### ISSUE THREAD

**Issue by Isayso** [bravepipeproject/BravePipeExtractor#1]
found your site via a NewPipe player for Rumble search.

Can you build an apk for your BraveNewPipe player? Thank you!

PS. For me there is no future for political or scientific videos on Y..T...  Newest torture is to hide videos behind login page.

**Comment by evermind-zz** [comment]
will happen soon!

**Comment by evermind-zz** [comment]
https://github.com/bravenewpipe/NewPipe/releases/tag/v0.21.8-1.0.0
