### ISSUE TITLE
Timestamps backdated for Bitchute videos

### ISSUE THREAD

**Issue by gc-user** [bravepipeproject/BravePipeExtractor#103]
For some reason, the timestamps seem to be backdated for Bitchute videos.

I haven't discovered the rule by how many hours and why, but some Bitchute videos, that were just (at the most 1 hour earlier) posted, are displayed in BravNewpipe as posted a few hours ago, others as almost a day ago (like 22 hours ago).

This, of course, is annoying, as new Bitchute videos get "buried" in the list of videos under videos from other platforms lile Youtube and Rumble that are in reality older than the Bitchute videos.

Maybe it has something to do with the time zone of the uploader in relation to the UTC time zone - Bitchute displays an UTC time stamp under all videos (seen when using a web browser). Maybe the time zone of the viewer (bravenewpipe user) in relation to the UTC time zone or the one of the uplader, respectively, plays a role.

Is it just me, or are other users experiencing the same phenomenon?

If so, would it be possible the modify the extractor for Bitchute videos to correct this issue?

Thank you!

**Comment by evermind-zz** [comment]
If I understand you correctly you meant that videos of the channels you subscribed to have ordering problems?

**Comment by gc-user** [comment]
Thanks for replying!

Not sure what you mean by that, so I describe it in a different way.

Let's assume you use BraveNewPipe. You are subscribed to a few channels. Channels on Youtube, Bitchute and Rumble.

If you update the "news feed" (or whatever the term is) that shows the new videos on all the channels you are subscribed to, the videos are sorted by update time, newest first (on top of the list).

If you happen to have subscribed to a channel on Youtube and on Bitchute, in the scenario I described in the first post, the video on the Bitchute channel will show up as being posted several hours (up to like 22h e.g.) back, even though it was just posted 1h ago or so, and the same video on the Youtube channel is displayed correctly as being posted like 1h ago.

So, now, if you are subscribed to multiple channels and some channels being banned from Youtube only having a presence on Bitchute, you always have for scroll way down just to make sure you're not missing a new Bitchute video, because they are all backdated (or is the correct term forward-dated in this case?), but for some reason apparently not with a fixed amount of hours for all videos / Bitchute channels, and are thus buried way down in the list of videos (from Youtube and Rumble channels) that are in reality posted before the Bitchute videos and should show up below them in the list. And of course, if one doesn't know that a Bitchute channel one is subscribed to has released a new video, one has to scroll down just in case, not knowing how far back one has to go not to miss any new Bitchute videos.

It's not a sorting issue, the sorting is according to the timestamp which is shown as "xx hours ago" etc. It's the timestamp that's wrong which can be verified by looking up a respective Bitchute video on a computer using a browser which will show that the video hasn't been posted almost a day or half a day ago, but recently or maybe 1-2h ago, whatever the case might be.

And because the time difference of the true timestamp and the one BraveNewPipe claims isn't fixed, my guess is, that it has something to do with the time zone of the uploader vs. UTC or vs. the time zone of the BraveNewPipe user.

But as I don't know how the extractor reads the time stamp of Bitchute videos, I can't analyze that theory against different Bitchute channels and the assumed location of the channel operator.

The easiest way to confirm this "bug" (?) is to have a channel / video that uploads around a fixed time in the week. So you know it's been just uploaded - esp. it that video is from a live stream that just ended and can't possible be a video that had been uploaded a while ago and just now been made public. If that video that's just been uploaded shows up in BraveNewPipe as allegedly having been posted like 12 or 22h ago, you know there's something wrong - not knowing however what exactly, especially if it is not a fixed delta of hours between true time stamp and the one shown by BraveNewPipe (at least not fixed for different Bitchute channels - I haven't taken notes to verify if the delta is fixed per each Bitchute channel, i.e. for the presumed time difference of the uploader and either UTC (because in the browser, Bitchute time stamps show UTC time) or the BraveNePipe user's time zone. So, for US users watching US time zone based Bitchute channels, there might not be any or much of a delta and they might not even recognize this problem.

If I knew how BraveNewPipe extracts and maybe converts the time stamps of Bitchute videos, I could maybe come up with a better / clearer idea that is more helpful for tracking down the problem... but for now, this is the way I can try to convey the problem I'm having with they way BraveNewPipe is listing Bitchute videos.

There might be such a video describe above (video upload of a "just" finished live stream) due today. So I might be able to report a specific delta for a specific video.

**Comment by evermind-zz** [comment]
I've found the problem and will soon release a new version

**Comment by gc-user** [comment]
Great, thank you!

**Comment by gc-user** [comment]
Ok, I just installed [v0.25.2-2.1.2](https://github.com/bravenewpipe/NewPipe/releases/tag/v0.25.2-2.1.2). It still seems 15h off for a recent video: Posted around 2 pm UTC (so, around 2h ago), 4 pm my time, BNP says it's been posted 17 hours ago...

[Edit]
Interestingly enough, a different video (different channel, presumably different time zone of uploader) that was posted around 7:30 am UTC (8,5h ago) shows up in BNP as having been posted also around 17h ago. That only ~8,5h delta. Not sure what to make of it...
[/Edit]

Any settings (in app or Android in general) I could / should check?

**Comment by evermind-zz** [comment]
@gc-user what is your timezone?

**Comment by gc-user** [comment]
UTC -2 hours / WEST

**Comment by evermind-zz** [comment]
Oh man, I fixed a bug that is not related to your problem. I gonna look into it again

**Comment by gc-user** [comment]
Ok, but you did fix a bug, so it wasn't wasted time and effort.
Thanks for your work.

**Comment by evermind-zz** [comment]
For the 'news feed' the upload dates from the channel page are used and Bitchute only shows the date without any time. There is no usable way to get the exact upload dates, thus you have a mess in your timeline. Sorry there is no fix possible.

**Comment by gc-user** [comment]
I see. That explains it then. Thanks for the detective work!

**Comment by evermind-zz** [comment]
There might be a way to get more specific timestamps information via rss feed. But they are limited to only the first I guess 10 videos - but that might be enough. The one thing I've to figure out before implementing, is how to look for channels with spaces in their names.

Eg
https://www.bitchute.com/feeds/rss/channel/ProtestantProduction works but https://www.bitchute.com/feeds/rss/channel/Reality%20Tester won't

edit: I figured it out: It seems using the name specified in:
```html
<div class="details">
<p class="name"><a href="/channel/reality-tester/"
````
works

**Comment by gc-user** [comment]
Cool! Thanks for the digging and congrats for finding a workaround solution!
The few recent videos having a time stamp and showing up at the correct place in the news feed list would definitely be enough for me.

Thanks!

**Comment by evermind-zz** [comment]
Please test the newest version https://github.com/bravenewpipe/NewPipe/releases/tag/v0.25.2-2.1.3

**Comment by gc-user** [comment]
Thanks for your efforts!

Looks good.
Luckily, a channel that is on Youtube, Bitchute and Rumble just released a new video earlier. With the new version, they all show up one after another in the "new videos feed", as they should, assuming they were uploaded around the same time.

Also, other Bitchute videos from earlier today / late yesterday, seem to show up further up in the list, i.e. being listed as not as old as with the previous version earlier today, i.e they probably show up now with a different, probably the correct time stamp.

I'm expecting another Bitchute channel to release an new video later today, which in the past just after being uploaded showed up as having been uploaded like 22h ago. I'll take that as the litmus test.

But for now, I'll assume that the problem is solved.

Thanks again!


[Update]

I guess you did it!
The notorious Bichute channel the new videos of which showed up as like 22h old when just posted with the old version, now showed up as a few minutes ago.

Well done, thank you very much for your efforts and persistence!
