### ISSUE TITLE
Bitchute channels not loaded anymore for "news" section

### ISSUE THREAD

**Issue by gc-user** [bravepipeproject/BravePipeExtractor#108]
Since a few days, maybe 3 or 4?, Bitchute channel seem to not be loaded when refreshing the "news" section. When going to each Bitchute channel directly, the latest videos show up (if there are any since the issue appeared).

Maybe Bitchute changed the rss api slightly?

**Comment by gc-user** [comment]
In case this is connected and helps with the pinning down of the cause: The channels' icons aren't loaded either anymore, not even when loading a channel from the channel list.

**Comment by evermind-zz** [comment]
I fixed that now!

**Comment by gc-user** [comment]
Ok, thank you very much. I'll be testing and reporting back once it's released.

**Comment by gc-user** [comment]
Thanks for the new release. I tested it. Apparently the fix may have broken the time stamp fix from a [previous release](https://github.com/bravenewpipe/NewPipeExtractor/issues/103). The time given in the new videos of subscribed channels for Bitchute videos seems to be based just on the date and calculated for UTC time instead of the specific time on that day.

**Comment by gc-user** [comment]
Update:

Further testing / observations:

Bitchute channels are (still) not being loaded in the "news" section and channel avatars seem to only be loaded in the "subscribed channels" section if a particular channel was tapped on and loaded so that the image got downloaded into cache (my guess). Then, when going back to channel list that particular avatar is now displayed, any avatar of any other Bitchute channel that has not been visited is not shown in the channel list.

**Comment by evermind-zz** [comment]
They changed the place where I've extracted the channel name. I have a fix but need some further testing

**Comment by gc-user** [comment]
I see, thanks for your efforts!

I made further tests with clearing the app's cache. At first it seemed promising, but I think it didn't change anything.
