### ISSUE TITLE
Question: conscrypt?

### ISSUE THREAD

**Issue by msalini** [bravepipeproject/BravePipeExtractor#110]
Pardon the question but ... what is the difference between the conscrypt and "non conscrypt" apk?

**Comment by evermind-zz** [comment]
Initially conscrypt version was for KitKat only as its security provider lack support for modern TLS encryption stuff. Conscrypt provides modern TLS encryption. Nowadays as KitKat is no longer supported by NewPipe and higher android versions have modern TLS support it is a leftover and not really needed. But if someone wants to have a "up-to-date" security provider you could use the conscrypt version.
