### ISSUE TITLE
Rumble download options mislabeled?

### ISSUE THREAD

**Issue by gc-user** [bravepipeproject/BravePipeExtractor#112]
It seem like Rumble changed the available video resolutions, making BNP's download options a mismatch.

Apparently, there is 1080p, 720p, 480p and 360p available, but BNP might show (only) 720p, 480p, 240p, 180p.

I haven't checked BNP's download options 720p, 480p and 180p, but 240p is in reality 360p. 180p seem too small a file to contain a viable video.

So, it's probably in part just a cosmetic issue (360p mislabeled as 240p), but it may need updating to make 1080p available for download, checking if 180p is really pointing to a viable video file, and checking if 720p and 380p match what the label says.

**Comment by evermind-zz** [comment]
thanks for reporting. Could you provide links where you have this problem? The resolution label is taken from rumble itself. But I found out that they use a 180 resolution stream that is just the timeline with low fps. I will remove it from the list

**Comment by gc-user** [comment]
Thanks for your reply.

I just searched for a random video. Most of them seemed to have the 360p option... So, apparently, this isn't a consistent or even a very common issue.

The following one I found exhibits the previously described issue:

https://rumble.com/v3u0e8j-instant-regret-fail-compilation-funny-fails-4.html

**Comment by evermind-zz** [comment]
I can confirm your findings - but still it is wrongly brought to us by rumble. They also provide their stream info in its metadata and there it is correct but now we have videos that have two 360 streams but with different bitrates. I will try to label them now eg: 1080p@2000k to distinguish the streams

**Comment by gc-user** [comment]
Yeah, I've seen that, too, on a browser, 2 different 360p streams for some videos.
In general this issue isn't really a big problem, I just reported it because Rumble might have changed more than I was noticing, and eventually change so much that the extractor wouldn't work at all anymore.
