### ISSUE TITLE
Rumble channels turning up empty, their videos not showing up in the "What's new" tab either.

### ISSUE THREAD

**Issue by gc-user** [bravepipeproject/BravePipeExtractor#119]
For the last few days, maybe even up to two weeks, Rumble seems to either have problems or changed something.

To check for consistency, I went ahead and simply searched for the term "test". Many videos show up, from different channels. Going to a search result (video) and then to the respective channel shows the respective channel empty, i.e. no videos showing up, although I just came to the channel via one of their video.

For some reason, some videos / channels I tested defied logic (consistency) and did show videos when going from the video to the channel.

Channels I came across this way and are showing up empty:
NASA, spaceXcentric, The Full English Show, Alarm Grid Home DIY Videos, Always keep smile, SOLUCUFFIE, PUBG, AI Reporter, Modern Castle

Channels that show videos:
ToJestDoja, vickypariyar5758, kuraderaj07

I'm not sure what to make of it.

Hold on, maybe I do. Using a browser I noticed that all "not working" channel are showing up as rumble.com/c/[name], all "working" channels are showing up as rumble.com/user/[name]. So, maybe rumble changed something with the "channels" (c) vs the "users" (user)...

Bitchute is also not showing up videos in the "What's new" section either, but this "bug" is happening less consistent with Bitchute than with Rumble, so I have even less lead on that. Also, it those can (at least at times) be "forced" to show up by reloading (on the "What's new" tab) several times.

Those problems might be because those platforms are under "attack", their servers are flaky or they changed something regarding their syntax / api. So, it might be temporary or here to stay.

**Comment by Theoinf0** [comment]
Yes I can attest that. Rumble channels won't open with populated videos under BraveNewPipe but tapping on "open this in browser" open them normally like properly working channel.

**Comment by kasim1011** [comment]
Yes, Rumble video no longer appearing in feed. And the channels profile doesn't show videos either.

**Comment by evermind-zz** [comment]
They changed stuff. It is fixed with 550c35f

**Comment by gc-user** [comment]
Thank you very much for the fix and the implementation of the big upstream changes (tabs)!

I won't open a issue for the recaptcha problem on Bitchute as you apparently are already aware of it per the changelog.

I noticed one minor thing regarding Bitchute: On a channels video page (if it loads successfully), under the video title where the channel name should be, there is now "CHANNEL_TAB_VIDEOS", same is true for the "What's New" tab, but curiously, in that list only channels that have "_" (underscore) in their name seem to be affected.
But you might already aware of that, too.
