### ISSUE TITLE
is the project still alive?

### ISSUE THREAD

**Issue by ruboard** [bravepipeproject/BravePipeExtractor#121]
is the project still alive?
Should we expect an update?
the original newpipe has long been updated to 0.26.1

**Comment by evermind-zz** [comment]
Still alive but lack of time. I will try to find some time

**Comment by ruboard** [comment]
Fortunately or unfortunately, I find your bravenewpipe the best among other forks. the combination of sponsorblock, improved search and now the new newpipe 0.26 with contributions to channels, none of them have!

**Comment by evermind-zz** [comment]
v0.26 has massive changes due to the introduction of tabs - so I have to rework the additional services quite a bit and also the Rumble has changed a lot.
