### ISSUE TITLE
problem loading thumbnails and avatars on YouTube

### ISSUE THREAD

**Issue by ruboard** [bravepipeproject/BravePipeExtractor#122]
In Russia, by an idiotic decision of the authorities, the domain yt3.ggpht.com is blocked; this prevents the normal loading of thumbnails and avatars on YouTube. In the application, sometimes you have to wait a very long time for them to load.
In browsers, the workaround is to redirect this domain to yt4.ggpht.com
Is it possible to somehow take this nuance into account?

Approximately the same situation is observed with soundcloud
soundcloud.com is blocked, m.soundcloud.com is not.

**Comment by evermind-zz** [comment]
if okhttp has the ability to replace URLs on the fly this could be implemented. I may look into it -- but unfortunately I've no time.

**Comment by ruboard** [comment]
I'm not an expert.;) It seemed to me that this could be solved simply by adding the appropriate links to the manifest
What can I say, I can only hope for your skill)

**Comment by evermind-zz** [comment]
As I suspected okHttp has the features to do this.

[replace-hosts.zip](https://github.com/bravenewpipe/NewPipeExtractor/files/14289476/replace-hosts.zip)

Try this version. First goto settings -> BraveNewPipe Settings -> Replace restricted hosts

The first (youtube) option works for me.
The 2nd and 3rd (both soundcloud) will probably not work at all. The 2nd is soundcloud.com -> m.soundcloud.com the 3rd is soundcloud.com -> replacing with the ip of soundcloud.com

If the apk is not installable, please let my know

**Comment by ruboard** [comment]
Thank you for being interested in fixing this.
Unfortunately, not a single option worked.
I have pcapdroid, there have not been a single request for yt4.ggpht.com. channel avatars appear as before with a delay of up to a minute, user avatars in comments do not load at all
for soundcloud I see that there are packets and dns and http 443 on m.soundcloud.com,
but nothing is loaded at all.

**Comment by evermind-zz** [comment]
Have you seen any requests for yt3.ggpht.com?

But if they block how could they appear later?

**Comment by ruboard** [comment]
![Screenshot_20240215-193332](https://github.com/bravenewpipe/NewPipeExtractor/assets/79255903/c595b709-3315-40ae-ad89-cbbb3434866a)
When you open any video, avatars in the comments are not loaded. the subject tries to load them, but to no avail.
as you can see, the packets leave but do not arrive.
There are no packages on yt4.ggpht, I don’t see them, neither with the option enabled nor with it disabled.
packages with clip thumbnails seem to go unhindered on i.ytimg.com round trip

**Comment by ruboard** [comment]
Tell me, maybe I'm getting ahead of myself.
Is it possible to implement a proxy based on a *.pac file using this method?

**Comment by evermind-zz** [comment]
I don't know much about pac files and its capabilities. 

But regarding the issue. I've figured out that (Brave)NewPipe is using 2 OkHttp instances and I configured the wrong one.  Here I've hard coded the remapping for the 2nd Okhttp instance. (yt3.ggpht.com -> yt4..ggpht.com and soundcloud.com -> m.soundcloud.com

[replace-hosts-v2.zip](https://github.com/bravenewpipe/NewPipeExtractor/files/14302960/replace-hosts-v2.zip)

**Comment by ruboard** [comment]
Great, packets on yt4.ggpht ran in both directions. all avatars and other things are loaded without delay
in the case of soundcloud, nothing comes of it. Yes, I see that packages go to m.soundcloud.com without hindrance. but nothing is loaded at all. Apparently simple redirection is not enough.

Regarding pac files, I can only advise you to google it) there are a number of projects on Github.
Many browsers provide the ability to specify a pac file either with a simple link or locally.
this solves a number of problems depending on the source. for example, removing age, regional, etc. restrictions.

**Comment by ruboard** [comment]
In principle, this is no longer relevant. YouTube is completely blocked in Russia.
access is possible only through Proxy or VPN.
Leave or not this option is to decide past
In any case, I will benefit you for this modification
