### ISSUE TITLE
no title picture shown of any Rumble video in search and on details page

### ISSUE THREAD

**Issue by evermind-zz** [bravepipeproject/BravePipeExtractor#13]
I can narrow down the error:
It works with v0.21.9-1.0.1: BraveNewPipe Release 0.21.9-1.0.1 and stopped working with v0.21.10-1.0.2: BraveNewPipe Release 0.21.10-1.0.2.
Here the error log
{"user_action":"load image","request":"https://sp.rmbl.ws/s8/1/d/V/i/C/dViCc.OvCc-small-Dr.-Rand-Paul-Democrats-won.jpg","content_language":"de-DE","content_country":"DE","app_language":"de_DE","service":"Rumble","package":"com.github.bravenewpipe","version":"0.21.13-1.0.3","os":"Linux Android 4.4.2 - 19","time":"2021-10-29 11:53","exceptions":["com.squareup.picasso.NetworkRequestHandler$ResponseException: HTTP 504\n\tat com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:51)\n\tat com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:219)\n\tat com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:175)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:237)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)\n\tat java.lang.Thread.run(Thread.java:841)\n\tat com.squareup.picasso.Utils$PicassoThread.run(Utils.java:354)\n"],"user_comment":""}

**Comment by bravepipeproject** [comment]
This was fixed  https://github.com/bravenewpipe/NewPipe/commit/5c7afbf4d4ee28929814174ee7660747f995173d
