### ISSUE TITLE
can't list videos at bitchute, 

### ISSUE THREAD

**Issue by fastness2024** [bravepipeproject/BravePipeExtractor#133]
upgraded from [v0.25.2-2.1.6] to v0.26.1-2.1.9 
it seemed the bitchute stopped working, but rumble started to work
Mow it can't list videos under this channel at bitchute, , but can get info of the channel, e.g. www.bitchute.com/channel/NYZMjDr6JOG3/
It can play videos from this channel,  with a direct link, e.g.  www.bitchute.com/video/MeUPDva2LK4k/
With a browser,  the channel shows" Some videos are not shown due to your current sensitivity settings, click here to show them." I seems this channels has many contents not for children. 

Logcat got  this
[12_03-23-54-15_613.log](https://github.com/bravenewpipe/NewPipeExtractor/files/14582723/12_03-23-54-15_613.log)

1710305721.092 10213 24898 24898 W ResourcesCompat: 	at android.os.Handler.handleCallback(Handler.java:942)
1710305721.092 10213 24898 24898 W ResourcesCompat: 	at android.os.Handler.dispatchMessage(Handler.java:99)
1710305721.092 10213 24898 24898 W ResourcesCompat: 	at android.os.Looper.loopOnce(Looper.java:201)
1710305721.092 10213 24898 24898 W ResourcesCompat: 	at android.os.Looper.loop(Looper.java:288)
1710305721.092 10213 24898 24898 W ResourcesCompat: 	at android.app.ActivityThread.main(ActivityThread.java:7924)
1710305721.092 10213 24898 24898 W ResourcesCompat: 	at java.lang.reflect.Method.invoke(Native Method)
1710305721.092 10213 24898 24898 W ResourcesCompat: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
1710305721.092 10213 24898 24898 W ResourcesCompat: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
1710305721.100 10213 24898 24898 W ResourcesCompat: Failed to inflate ColorStateList, leaving it to the framework
1710305721.100 10213 24898 24898 W ResourcesCompat: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f040119 a=-1}, theme={InheritanceMap=[id=0x7f130146com.github.bravenewpipe:style/DarkTheme.Rumble, id=0x7f130142com.github.bravenewpipe:style/DarkTheme, id=0x7f130011com.github.bravenewpipe:style/Base.DarkTheme, id=0x7f1300c6com.github.bravenewpipe:style/Base.V29.DarkTheme, id=0x7f1300c0com.github.bravenewpipe:style/Base.V27.DarkTheme, id=0x7f1300a4com.github.bravenewpipe:style/Base.V21.DarkTheme, id=0x7f130009com.github.bravenewpipe:style/Base, id=0x7f1300c4com.github.bravenewpipe:style/Base.V29, id=0x7f1300becom.github.bravenewpipe:style/Base.V27, id=0x7f1300a2com.github.bravenewpipe:style/Base.V21, id=0x7f130295com.github.bravenewpipe:style/Theme.AppCompat.DayNight.NoActionBar, id=0x7f1302a2com.github.bravenewpipe:style/Theme.AppCompat.NoActionBar, id=0x7f13028dcom.github.bravenewpipe:style/Theme.AppCompat, id=0x7f130050com.github.bravenewpipe:style/Base.Theme.AppCompat, id=0x7f1300c2com.github.bravenewpipe:style/Base.V28.Theme.AppCompat, id=0x7f1300bbcom.github.bravenewpipe:style/Base.V26.Theme.AppCompat, id=0x7f1300b5com.github.bravenewpipe:style/Base.V23.Theme.AppCompat, id=0x7f1300b3com.github.bravenewpipe:style/Base.V22.Theme.AppCompat, id=0x7f1300a7com.github.bravenewpipe:style/Base.V21.Theme.AppCompat, id=0x7f1300c8com.github.bravenewpipe:style/Base.V7.T
[12_03-23-54-15_613.log](https://github.com/bravenewpipe/NewPipeExtractor/files/14582725/12_03-23-54-15_613.log)
Thank you

**Comment by evermind-zz** [comment]
I've tried to load the channel! Here it is working although it is taking some time.
> With a browser, the channel shows" Some videos are not shown due to your current sensitivity settings, click here to show them." I seems this channels has many contents not for children.

BraveNewPipe takes that into account and adds the showAll=1 parameter when fetching

**Comment by fastness2024** [comment]
It seemed this issue happened at those subscript channels at Bitchute. 
By searching for "Jim Crenshaw", I could find his channel, and got all his videos fetched / played well. 
Then, I added his Bitchute channel to the subscriptions. None of his videos got fetched anymore. Other info of this channel still posted.

The same issue happened to all Bitchute channels, after imported from previous Subscriptions .json files, or Settings/ Content /Import datebase .zip files. Meanwhile, all youtube/Rumble channels worked well.
