### ISSUE TITLE
YouTube comments don't show and UI error shows.

### ISSUE THREAD

**Issue by ghost** [bravepipeproject/BravePipeExtractor#139]
YouTube comments don't show properly and UI error shows and sometimes the app crashes. And sometimes on YT short videos when I full screen the screen glitches out. And it takes 2 seconds for the vid fullscreen to load.

**Comment by ruboard** [comment]
NewPipe 0.27.0 released
comments have been fixed

We are waiting for an update from the respected developer of the subject

**Comment by timur-g** [comment]
This was fixed, so needs to be closed.
Different issue is that YT may not work now in 0.27.1.
