### ISSUE TITLE
Rumble: Titles missing in video list

### ISSUE THREAD

**Issue by rogerdc** [bravepipeproject/BravePipeExtractor#153]
Running version 0.27.0-2.1.10

### To reproduce:

1. Subscribe to a channel on Rumble.
2. Load the channel's page

### Expected result:

Videos will show titles.

### Actual result:

Titles are missing.

![Screenshot_20240626-033137](https://github.com/bravenewpipe/NewPipeExtractor/assets/4684857/99d787d0-840d-4f94-8e6f-2d3e029a72ea)

**Comment by gc-user** [comment]
I can confirm this.

**Comment by mcgeezy** [comment]
0.27.0-2.1.10 

Same here

![Screenshot_2024-07-06-15-57-55-07_111e0f0a6b6c27a0b544aee7364834f5](https://github.com/bravenewpipe/NewPipeExtractor/assets/1297874/d9f94404-f369-4d70-bc94-938c699d8562)

**Comment by evermind-zz** [comment]
fixed in [v0.27.0-2.1.11](https://github.com/evermind-zz/bnp-testing/releases/tag/v0.27.0-2.1.11)

**Comment by rogerdc** [comment]
It's working! Thank you!
