### ISSUE TITLE
Bitchute broke BraveNewPipe's access... again

### ISSUE THREAD

**Issue by gc-user** [bravepipeproject/BravePipeExtractor#155]
Apparently, Bitchute made some changes (maybe around the 25th or 26th of June 2024) that broke the access using BraveNewPipe (v0.27.0-2.1.10). Channels show error message instead of videos, search doesn't work and neither does "recent", "hot" etc. But I never used the last mentioned, so I don't know if that worked before. But the first two test scenarios are basic stuff and worked before.

Thanks for looking into this!

**Comment by evermind-zz** [comment]
they redone their whole site access. They've now another API that has all the goodies.. So far I got the searching kind of working again... but lots stuff to do

**Comment by gc-user** [comment]
Yeah, I noticed that, too, after I made the issue report, that the website looks totally different now. I forgot to update my post... :-)

Thanks for looking into it! The new API doesn't sound that bad, if I understand you correctly. Just more work to make the switch...

**Comment by gc-user** [comment]
Apparently, there an "old Bitchute" still online, maybe you could bulk-replace the the code to direct it to that url to make Bitchute work until the new api is implemented? Unless there's no api access to the old bitchute, of course...

https://old.bitchute.com

**Comment by evermind-zz** [comment]
fixed in https://github.com/bravenewpipe/NewPipe/releases/tag/0.27.1-2.2.0

**Comment by gc-user** [comment]
Thank you very much!
