### ISSUE TITLE
YouTube stopped working, we are waiting for an update from TeamNewPipe

### ISSUE THREAD

**Issue by ruboard** [bravepipeproject/BravePipeExtractor#157]
YouTube stopped working, we are waiting for an update from TeamNewPipe
I hope the respected developer will not leave us and will release an update after NewPipe

**Comment by evermind-zz** [comment]
I pulled the fix from the pullrequest. Youtube should work again

**Comment by gc-user** [comment]
That was fast! Thank you very much!
Released even before Newpipe released their fixed version! :-)
