### ISSUE TITLE
...and Bitchute also messed with their access again...

### ISSUE THREAD

**Issue by gc-user** [bravepipeproject/BravePipeExtractor#160]
Just one day after Youtube, Bitchute, too, made the recent changes / update to BraveNewPipe incompatible again.
Loading a channel'page or videos in the "what's new" tab doesn't work anymore.

Maybe it's just a slight change to the major changes before, I don't know.

Bitchute really steps into Youtube's footsteps regarding making too many changes, too often... :-)

**Comment by evermind-zz** [comment]
fixed in https://github.com/bravenewpipe/NewPipe/releases/tag/v0.27.2-2.2.1

**Comment by gc-user** [comment]
Thank you very much for the quick fix!
