### ISSUE TITLE
Please add Jubitu.com

### ISSUE THREAD

**Issue by timur-g** [bravepipeproject/BravePipeExtractor#171]
BRAVE is great and unique app. There are multiple NP forks, this being the only one I know adding services so that we may watch outside huge but censored YT.
We still may have a wish for new services and here is a kind request.

Please add JUBITU.COM as a service so that videos may be seen and searched.
Seems that we may watch a single video of at have link, but not open the main page, browse or search.

**Comment by Danish-Vidar** [comment]
Why not just add it yourself?

Settings -> Content -> PeerTube instances
![Screenshot_20241222-230230](https://github.com/user-attachments/assets/9c9a23b7-ff34-4335-b04a-4e4df91aa84a)

**Comment by timur-g** [comment]
Thanks! I had no idea. Works.
Only small issue is that in main list I see a single item (last selected in PeerTube) and other added instances are in submenu. Not so important, if it had to be like that.
I thick this may be closed.
