### ISSUE TITLE
Indicate which source?

### ISSUE THREAD

**Issue by strider72** [bravepipeproject/BravePipeExtractor#20]
It would be awesome if the app could show an icon or similar indicator of where each video or channel comes from. On a list of subscriptions or new videos, there's no easy way to distinguish Rumble from YouTube, for example

**Comment by evermind-zz** [comment]
Thats true! That would be a good feature!

**Comment by evermind-zz** [comment]
closed in favor of https://github.com/bravenewpipe/BraveNewPipeLegacy/issues/1
