### ISSUE TITLE
Add SponsorBlock and ReturnYouTubeDislikes to BraveNewPipe

### ISSUE THREAD

**Issue by JoshuaKimsey** [bravepipeproject/BravePipeExtractor#30]
I just recently ran across this fork of NewPipe and love the idea of including other platforms like Rumble, Bitchute, and Odysee (Hopefully!) to the NewPipe format. Up until now, I've been using a [fork](https://github.com/polymorphicshade/NewPipe) of NewPipe that Includes SponsorBlock and the ReturnYouTubeDislike features added to it. I was wondering if such things could also be added to BraveNewPipe as well? SponsorBlock is something I personally don't use, but I know many do, however the dislike counter being added back is something I do like a lot.

If these features could be added to BraveNewPipe as well, it would really make this fork even better than the standard NewPipe. Perhaps y'all could even combine your efforts to make a unified NewPipe fork that is better than the original, though I'd still be perfectly fine with just having the added functionality of the SB fork added. :)

**Comment by wepache** [comment]
I was actually on my way to ask for this feature myself. Glad someone has requested it. I am moving from the Sponsorblock version to BraveNewpipe but I am truly saddened that Sponsor block is not a part of this fork.

**Comment by LeonryLight** [comment]
I would love if that was added here too. Considering it was already added to another fork of NewPipe, is it too difficult to just move the already existing code to here?

**Comment by Cryptophunk** [comment]
Both of the forks have experienced the same hostility from TeamNewPipe. I wonder if the developers would consider teaming up and making an all in one fork?

**Comment by json-by-jason** [comment]
Although both forks have experienced hostility from TeamNewPipe, it's two different kinds: SponsorBlock was blocked based on a privacy concern, but platforms like rumble are blocked based on political concern. "Teaming up" wouldn't improve workflow for either of these developers because they are not trying to solve the same problem.

**Comment by Cryptophunk** [comment]
> Although both forks have experienced hostility from TeamNewPipe, it's two different kinds: SponsorBlock was blocked based on a privacy concern, but platforms like rumble are blocked based on political concern. "Teaming up" wouldn't improve workflow for either of these developers because they are not trying to solve the same problem.

I just assumed the problem NewPipe and it's forks are trying accomplish is creating an app that can extract many different media sources. Forks obviously have their own feature adds but the main problem they all focus on fixing is a central place to access media online.

**Comment by Mr-Bajs** [comment]
Yes, the fork with sponsorblock added is a better than Newpipe itself. So i wonder if not it would be better to just base this fork of Newpipe x Sponsorblock instead of Newpipe. No need to team up for that.

**Comment by evermind-zz** [comment]
> Yes, the fork with sponsorblock added is a better than Newpipe itself. So i wonder if not it would be better to just base this fork of Newpipe x Sponsorblock instead of Newpipe. No need to team up for that.

I'll give it a try. -- Last time I tried it -- long ago -- other video platforms just crashed.

**Comment by evermind-zz** [comment]
It works! Please test!
[bnp-Sponsorblock-Debug.zip](https://github.com/bravenewpipe/NewPipeExtractor/files/10717850/bnp-Sponsorblock-Debug.zip)

**Comment by Cryptophunk** [comment]
Hey man thats awesome! It works for me too! Maybe we should just end up calling this repo Newpipe X as its 10x better than the main branch.

**Comment by Mr-Bajs** [comment]
It works fine! :)

**Comment by Cryptophunk** [comment]
> It works! Please test!
> [bnp-Sponsorblock-Debug.zip](https://github.com/bravenewpipe/NewPipeExtractor/files/10717850/bnp-Sponsorblock-Debug.zip)
> 

One thing I might reccomend is changing the rumble header color to green, but other than that everything seems to be working smoohtly. I had no issues importing my subscriptions but had some issues importing old database and settings.

**Comment by Mr-Bajs** [comment]
The dev of the popular fork of [NewPipe x SponsorBlock x Return YouTube Dislike](https://github.com/polymorphicshade/NewPipe) doesn't have any issues with adding additional sources according to this [comment](https://github.com/polymorphicshade/NewPipe/issues/225#issuecomment-1229571745). But won't do the extra work for that to happen himself, but willingly accepts PR from anyone that does.

Since this seams to work well, then maybe just adding PR onto that project instead?

**Comment by evermind-zz** [comment]
Integrated with release  0.25.1-2.1.0
