### ISSUE TITLE
YouTube still broken (2 weeks) 

### ISSUE THREAD

**Issue by degarb** [bravepipeproject/BravePipeExtractor#51]
23.1 has not worked with YouTube for 2 weeks.

I like to have NewPipe and Bravenewpipe installed because Android rolls the dice and scrambles the 50 possible programs that I can share a video with. With 2 programs, I double the chances that I will see one of the two, and save myself a lot of time, since I use these two programs to download the audio (and sometimes the video) of something like 600 videos per month, to listen to at work. I also share about 120 videos to the video player per month on top of watch later list, before I go to bed.

This is why I am anxious to get the 23.2, youtu.be fixed, version of Bravenewpipe in addition to the working 23.2 NewPipe. It will save me a great bit of time over the next month.

I never successfully compiled any program other than basic and aitohotkey. I can barely find the apks in github, as the entire github concept seems alien to me, despite doing a github tutorial. So, it is unlikely that I can grab working NewPipe code, and then, paste it into bravenewpipe, then compile it--the most likely 15 minute fix.

**Comment by degarb** [comment]
There should be a setting in the app that forces the choice to the top of the Android share list which scrambles what seems like hundreds of app icons, making it time consuming to find bravenewpipe among the random mess... I have not found any working share apps on the playstore that did not have a bigger downside than upside.

**Comment by ShareASmile** [comment]
Downloas from Releases 
https://github.com/bravenewpipe/NewPipe/releases/tag/v0.23.1-1.1.1
