### ISSUE TITLE
Bitchute comment support

### ISSUE THREAD

**Issue by Johnny5sword** [bravepipeproject/BravePipeExtractor#57]
Hi!

It would be nice to see the comments inside the app instead of opening the website to see it.

I think there are 3 aspects to this:
- Main comments
- Comment likes and dislikes 
- Comment replies ([AnimePipe](https://github.com/InfinityLoop1309/AnimePipe) and Newpipe PR 9020 has already integrated replies but only for YouTube)

**Comment by evermind-zz** [comment]
Can you try
[app-brave-debug.zip](https://github.com/bravenewpipe/NewPipeExtractor/files/10249925/app-brave-debug.zip)

This is implemented so far:
- Main comments (I think all comments are there but flat)
- Comment likes (upvotes) -- dislikes are not supported I think -- by NewPipeExtractor
- Comments replies will only be integrated if PR 9020 will be merged

It works but on some videos there is a sockettimeout as it takes ages to load the comments for the video. In Browser it also takes forever but finally works there.
