### ISSUE TITLE
rumble channel page broken + feed

### ISSUE THREAD

**Issue by ghost** [bravepipeproject/BravePipeExtractor#96]
Opening this to try to get ahead of the issue at hand. New rumble site backend update broke something I presume. 
As of today opening a creators page whether from subscription tab or through a video crashes. 

In addition rumble specific subscriptions no longer update on the lastest feed tab under "whats new" which queries all subs except rumble subs currently.

Note: rumble videos are still searchable and can be played only going to someones main channel page breaks.

Edit: same symptoms as #67

**Comment by MuhannadYT** [comment]
Same issue

**Comment by JeffersM1** [comment]
I noticed this yesterday also.  I have v0.25.1-2.1.0 of BraveNewPipe installed and lately I am not able to open channels on Rumble, so none of my subscriptions to Rumble channels are working. YouTube channels are still working fine.

I see the problem under the following conditions:
Click the Today's Battle Leaderboard Top 50 link
Click on any video
Click on the channel link
get error message: Sorry, something went wrong. Report. Retry. Open in browser.

Get the same result if I try to open a channel in my subscriptions list.

This used to work.

**Comment by evermind-zz** [comment]
I'll try to fix it tonight

**Comment by MuhannadYT** [comment]
> ```
> I'll try to fix it tonight
> ```

Appreciate it

**Comment by JeffersM1** [comment]
> 

Thanks for providing a great product.  I have been wanting something like this for a couple of years the could play streams from different streaming sites.  Its so much easier to have all subscriptions monitored from one place.

**Comment by evermind-zz** [comment]
should work with https://github.com/bravenewpipe/NewPipe/releases/tag/v0.25.1-2.1.1
